read a
echo "$a x 1 = $((a*1))"
echo "$a x 2 = $((a*2))"
echo "$a x 3 = $((a*3))"
echo "$a x 4 = $((a*4))"
echo "$a x 5 = $((a*5))"
echo "$a x 6 = $((a*6))"
echo "$a x 7 = $((a*7))"
echo "$a x 8 = $((a*8))"
echo "$a x 9 = $((a*9))"
echo "$a x 10 = $((a*10))"
